### ISSUE TITLE
ID & Documentation new modules

### ISSUE THREAD

**Issue by Rosen01** [velbus/moduleprotocol#3]
To start the implementation in OpenHAB integration, is it possible to have the ID & documentation of the new modules  ?

VMB2BLE-10
VMB4RYLD-10
VMBRYNO-10
VMB6PB-20
VMB8IN-20
VMBDALI-20
VMBEL1-20
VMBEL1PIR-20
VMBEL2-20
VMBEL4-20
VMBELO-20
VMBGP1-20
VMBGP2-20
VMBGP4-20
VMBGPO-20
VMBGPPIR-20

**Comment by cereal2nd** [comment]
The same goes for the integration in home-assistant :)

**Comment by MDAR** [comment]
I've created a support ticket at
https://help.velbus.eu

Asking them to respond here

########
Velbus SL2 Ticket 
"New module tech details - third party support  (#9506)"

**Comment by MDAR** [comment]
FYI

`VMBxxxx-10` modules use the same firmware as original modules, just in new cases.
They will become `VMBxxxx-20` versions when new firmware has been created.

**Comment by silamon** [comment]
Thank you for your interest. The protocol manuals will be added soon. 

For the VMBxxxx-10 there's a difference in the module type packet (0xFF) since the new modules all support having a terminator. VMBxxxx-20 will be different from their previous revisions in some parts since we're aligning a few things.

**Comment by silamon** [comment]
All protocol manuals have been added that we can add. 
Other protocol manuals requested don't have a protocol manual at this moment.
